[package]
name = "lftcm2020"
version = "0.1"
lean_version = "leanprover-community/lean:3.49.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "36f5ed004d8eb2bae83fe6319b235464ff459797"}
