[package]
name = "lftcm2020"
version = "0.1"
lean_version = "leanprover-community/lean:3.38.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "df2d70d67999da49fecfaaaf64ac107642619b09"}
