[package]
name = "lftcm2020"
version = "0.1"
lean_version = "leanprover-community/lean:3.28.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "8e275a30511b92037c577c0ab20b2602d73abcca"}
