[package]
name = "lftcm2020"
version = "0.1"
lean_version = "leanprover-community/lean:3.38.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "1cfb97d5d3284898b762521f503f9dc72e9fe6aa"}
