[package]
name = "lftcm2020"
version = "0.1"
lean_version = "leanprover-community/lean:3.45.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "cd7b23d100351ff5c71e52d914580dec6d19734d"}
