[package]
name = "lftcm2020"
version = "0.1"
lean_version = "leanprover-community/lean:3.35.1"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "f3f4442562e00939880a56baa7b9ab0d5f19a570"}
