# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Home', path: '', url: ''}
- {name: 'Schedule', path: '', url: 'schedule.html'}
- {name: 'Participants', path: '', url: 'participants.html'}
- {name: 'Exercises', path: '', url: 'exercises.html'}
- {name: 'Contact', path: '', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'rss-square', link: '/feed.xml'}

sharing_button_prompt: 'Feel free to share!'

